version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          actions-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: "bun"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          dependencies:
              patterns:
                  - "*"
