name: Update bangs

on:
    schedule:
        - cron: "0 0 * * 1"
    workflow_dispatch:

jobs:
    update-bangs:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Update bangs
              run: bun scripts/update-bangs.ts

            - name: Push update
              run: |
                  if [[ -n $(git status --porcelain) ]]; then
                    git config user.name "github-actions[bot]"
                    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git add .
                    git commit -m "Update bangs"
                    git push
                  fi
